version: '3.4'
services:
  megamek:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    command: ["java","-Xmx1024m","-jar","MegaMek.jar","-dedicated","-password","$PASSWORD"]
    ports:
      - $PORT_RANGE:2346
    user: 1001:1001
